# Generated by Django 4.2.20 on 2025-04-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxmate_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='user_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='conversation_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
